### ISSUE TITLE
Generating the repository and authentication

### ISSUE THREAD

**Issue by jchappelle** [pf4j/pf4j-update#2]
Hi,

I'm currently looking into using your plugin framework. We have a monolithic web application built on wicket, spring and hibernate and I'm looking into ways to modularize pieces so we can focus releases on smaller parts of the application instead of having to roll out and QA the entire application even when one component is all that changed.

I prefer using a lightweight framework like pf4j over OSGI for many reasons I won't get into here. 

I understand the code part of how this works but now I'm trying to figure out how it affects our deployment. We use maven and have a nexus repository for our artifacts. If our plugin zip files are stored as artifacts in nexus it looks like your UpdateManager would work with this as long as the urls point to the artifacts. Here are my questions:

How do you suggest we build the repository json file? Also, is authentication supported? I would hope to not have to put username and password in the json file.

I suppose I could create a custom UpdateManager using your example but I wanted to check and get your opinion since I'm sure you have thought through some of these things already.

Thanks for the framework!

**Comment by decebals** [comment]
Hi

PF4J-update is built for simple things but I am sure that you can extend it to built something more complicated. Someone create a similar concept https://github.com/gitblit/gitblit-registry for one project.
The actual project is very light (4 files) so it's not a big deal. You can complicate for example `FileDownloader` to force an authentication process, in this case you have the freedom to choose a username/password authentication (in this case you can keep these credentials in database, file or other storage) or something else.

> We use maven and have a nexus repository for our artifacts. If our plugin zip files are stored as artifacts in nexus it looks like your UpdateManager would work with this as long as the urls point to the artifacts. 

In the form presented by you I don't see an advantage of nexus repository over actual storage format (plain file system). Why I want to keep plugins in a maven repository?

**Comment by jchappelle** [comment]
I wasn't suggesting you put your plugins in Nexus. I was simply saying the
FileDownloader would work with Nexus with the exception of authentication.

The reason we will store our plugins there is because that's where all our
artifacts are and we have deployment scripts and QA staging infrastructure
built around it.

I appreciate the answer. I may just build our own. I understand wanting to
keep your library simple.

Thanks
On Feb 17, 2016 7:31 AM, "Decebal Suiu" <notifications@github.com> wrote:

> Hi
>
> PF4J-update is built for simple things but I am sure that you can extend
> it to built something more complicated. Someone create a similar concept
> https://github.com/gitblit/gitblit-registry for one project.
> The actual project is very light (4 files) so it's not a big deal. You can
> complicate for example FileDownloader to force an authentication process,
> in this case you have the freedom to choose a username/password
> authentication (in this case you can keep these credentials in database,
> file or other storage) or something else.
>
> We use maven and have a nexus repository for our artifacts. If our plugin
> zip files are stored as artifacts in nexus it looks like your UpdateManager
> would work with this as long as the urls point to the artifacts.
>
> In the form presented by you I don't see an advantage of nexus repository
> over actual storage format (plain file system). Why I want to keep plugins
> in a maven repository?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/decebals/pf4j-update/issues/2#issuecomment-185204640>.
>

-- 



NOTICE: This electronic mail message and any files transmitted with it are 
intended exclusively for the individual or entity to which it is addressed. 
The message, together with any attachment, may contain confidential and/or 
privileged information. Any unauthorized review, use, printing, saving, 
copying, disclosure or distribution is strictly prohibited. If you have 
received this message in error, please immediately advise the sender by 
reply email and delete all copies.

**Comment by jchappelle** [comment]
I should mention. Our plugins will all be written internally by us so no
third parties will be developing them. If we were opening something up to
others then I would agree that Nexus with authentication would be a bad
choice.
On Feb 17, 2016 7:31 AM, "Decebal Suiu" <notifications@github.com> wrote:

> Hi
>
> PF4J-update is built for simple things but I am sure that you can extend
> it to built something more complicated. Someone create a similar concept
> https://github.com/gitblit/gitblit-registry for one project.
> The actual project is very light (4 files) so it's not a big deal. You can
> complicate for example FileDownloader to force an authentication process,
> in this case you have the freedom to choose a username/password
> authentication (in this case you can keep these credentials in database,
> file or other storage) or something else.
>
> We use maven and have a nexus repository for our artifacts. If our plugin
> zip files are stored as artifacts in nexus it looks like your UpdateManager
> would work with this as long as the urls point to the artifacts.
>
> In the form presented by you I don't see an advantage of nexus repository
> over actual storage format (plain file system). Why I want to keep plugins
> in a maven repository?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/decebals/pf4j-update/issues/2#issuecomment-185204640>.
>

-- 



NOTICE: This electronic mail message and any files transmitted with it are 
intended exclusively for the individual or entity to which it is addressed. 
The message, together with any attachment, may contain confidential and/or 
privileged information. Any unauthorized review, use, printing, saving, 
copying, disclosure or distribution is strictly prohibited. If you have 
received this message in error, please immediately advise the sender by 
reply email and delete all copies.

**Comment by decebals** [comment]
Thanks for clarifications. If you want to use the current base code and to extend this code in your direction (extract some concepts as interfaces or abstract classes and use custom implementation for your use case) I am happy to accept new PRs.

> I wasn't suggesting you put your plugins in Nexus. 

My question ("Why I want to keep plugins in a maven repository?") was a philosophical question :smile: I was sure that you do not propose me to put my plugins in Nexus.

Have fun

**Comment by janhoy** [comment]
@jchappelle Leaving a comment in this issue to let you know that after https://github.com/decebals/pf4j-update/pull/11 there is now support for pluggable Update Repositories. That means you can write your `NexusUpdateRepository` which could include a `NexusFileDownloader`. Then you have full control to look for plugins.json where you want, to add user/pass in the constructor of `NexusUpdateRepository` instead of in json files etc.

**Comment by decebals** [comment]
@jchappelle 
Can we close this issue?

**Comment by jchappelle** [comment]
@decebals sure.
