### ISSUE TITLE
How can detect new plugin during running application

### ISSUE THREAD

**Issue by dgks0n** [pf4j/pf4j-update#35]
I have an application (web application) was running and I have a plugin that follow pf4j mechanism with ZIP folder. I copied ZIP to my plugin folder but it could not detect automatically without restart server.

Do you have any solution?

**Comment by decebals** [comment]
This functionality is not implemented in PF4J. In the past, I wrote some code (on a feature branch) that deals with this aspect but I never finished/published my work. 
I think that you can do it yourself. What you need is to listen on new file in a directory (plugins directory). You can do it with nio `WatchService` from Java. When you detect a new plugin file (zip in your case) in `plugins` directory that call `PluginManager.loadPlugin(Path pluginPath)`.

You can take a look at [ReloadWatcher](https://github.com/pippo-java/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/reload/ReloadWatcher.java) from other project where I am involved.

If the implementation is simple enough you can share it with us (via Pull Request) and we can try to add this feature in the PF4J's core.

P.S I think that this issue (feature) is related to [pf4j project](https://github.com/pf4j/pf4j) and not to `pf4j-update` project.

**Comment by dgks0n** [comment]
I got your idea. Thank you so much!
