### ISSUE TITLE
lastPluginRelease Map never reset

### ISSUE THREAD

**Issue by loblanch** [pf4j/pf4j-update#37]
need a lastPluginRelease.clear() in the UpdateManger.refresh()
if you remove the lastest Plugin version, in the repository,  the map always return the removed Plugin that cause a crash.  I use the 2.1.0-Snapshot release. Thx!

**Comment by decebals** [comment]
Can you submit a PR? Thanks!

**Comment by decebals** [comment]
Solved with #38. Thanks!
