### ISSUE TITLE
The pluginsJsonFileName is not optional for repositories read from JSON files

### ISSUE THREAD

**Issue by hazemkmammu** [pf4j/pf4j-update#40]
I was using the repositories.json format in the README.md and skipped the pluginsJsonFileName property when defining repositories assuming 'plugins.json' will be used.

However since org.pf4j.update.UpdateManager.initRepositoriesFromJson() parses the org.pf4j.update.DefaultUpdateRepository from JSON, pluginsJsonFileName is null. The org.pf4j.update.DefaultUpdateRepository.initPlugins() throws a java.net.MalformedURLException when it tries to build the URL object for plugins.json.

I fixed this by specifying 'plugins.json' explicitly for all repositories, it would be nice if the default was used in case the JSON did not specify this. The org.pf4j.update.DefaultUpdateRepository.DefaultUpdateRepository(String, URL) does this.

**Comment by decebals** [comment]
Resolved by #42.
