### ISSUE TITLE
Please consider introducing a unit-testing framework

### ISSUE THREAD

**Issue by hazemkmammu** [pf4j/pf4j-update#41]
It would make it a lot easy for the community to contribute to the project without worrying too much about introducing new bugs. I can create a PR if you don't mind.

**Comment by decebals** [comment]
JUnit and Mockito are already available in `pom.xml`, as dependencies. What other framework you want to introduce?

**Comment by hazemkmammu** [comment]
My apologies. I only looked at the classes org.pf4j.update.RepositoriesTest and org.pf4j.update.UpdateTest which had a main method with test calls.

**Comment by decebals** [comment]
@hazemkmammu 
I understand. Yes, they are not unit tests. I think that in the end we can transform/convert them in unit tests.
