### ISSUE TITLE
URI is not hierarchical

### ISSUE THREAD

**Issue by otmanel31** [pf4j/pf4j-update#43]
Hi Decebals,

When i try to update my plugins, i face an issue: java.lang.IllegalArgumentException: URI is not hierarchical. This happened may be when pf4j update try to open json file and only on windows OS. On linux, that works fine.

**Comment by decebals** [comment]
Give me more information:
- what type of plugins (jar, zip, ...)
- what version of pf4j, pf4j-update
- add a stack trace of error

**Comment by decebals** [comment]
@otmanel31 Ping

**Comment by otmanel31** [comment]
i don't try it again on windows for a moment ... all dev done are under linux os that are ok. I think we can close it ?

**Comment by decebals** [comment]
I will close it. Please reopen it if you have new information. Thnaks!
