### ISSUE TITLE
Incompatible with pf4j 3.x because PluginException not found

### ISSUE THREAD

**Issue by pranavram-n** [pf4j/pf4j-update#44]
I'm using
pf4j 3.0.1
pf4j-spring 0.5.0
pf4j-update 2.1.0

As I try to build the project, I see
```
error: cannot access PluginException
...
class file for org.pf4j.PluginException not found
```

I see [here](https://github.com/pf4j/pf4j/blob/master/CHANGELOG.md#300---2019-06-12) that `PluginException` has been changed to `PluginRuntimeException`. The master branch of `pf4j-update` seems to reflect this as well. But the code for v2.1.0 from maven central seems to contain this older version:

```java
    public boolean updatePlugin(String id, String version) throws PluginException {
        if (pluginManager.getPlugin(id) == null) {
            throw new PluginException("Plugin {} cannot be updated since it is not installed", id);
        }
        ...
```

Has the new version not been released yet, or am I somehow getting an older version when I specify 2.1.0?

**Comment by decebals** [comment]
Thanks for reminding me that I have to release a new version.
The issue is known (see [forum](https://groups.google.com/forum/#!topic/pf4j/IlsORzxQ4eM)).
I promoted the SNAPSHOT version as `2.2.0`.

**Comment by decebals** [comment]
After you try the new version, if everything is OK, please close this issue.

**Comment by pranavram-n** [comment]
Works fine with `2.2.0`, thanks!
