### ISSUE TITLE
2.4.0-SNAPSHOT available via Maven

### ISSUE THREAD

**Issue by ludup** [pf4j/pf4j-update#51]
I don't see a 2.4.0-SNAPSHOT in the Sonatype snapshot repository.

Can we get a snapshot built? I'd like to test my recent contribution via a deployed snapshot.

**Comment by decebals** [comment]
@ludup 
I published the first version of [2.4.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/pf4j/pf4j-update/2.4.0-SNAPSHOT).

**Comment by ludup** [comment]
Appreciate that. Thanks.
