### ISSUE TITLE
Updatemanager fails because of Files.exists

### ISSUE THREAD

**Issue by sagarvilas** [pf4j/pf4j-update#52]
I am trying to update a plugin after deploy and this is failing. 
On debugging I noticed that in org.pf4j.update.UpdateManager.refresh() method Files.exists returns false, and I think this is expected behavior as the value of "repositoriesJson" is "repositories.json". I think "repositoriesJson" should have absolute path, a possible solution might be to make path an user provided property. 
Let me know what you think

**Comment by decebals** [comment]
@sagarvilas 
Can you check with the latest SNAPSHOT version?  Maybe the problem was solved by https://github.com/pf4j/pf4j-update/pull/48.
If the problem persists, please try to debug the `pf4j-update` code (put a breakpoint and display some values) and put some details in a new comment.

**Comment by sagarvilas** [comment]
Hi @decebals just checked the #48 commit, and "Files.exists(repositoriesJson)" in line 222 is the culprit as it returns false even if the file exists. Below is the version I am using.
  compile group: 'org.pf4j', name: 'pf4j-update', version: '2.3.0'

**Comment by sagarvilas** [comment]
Hi @decebals this is the fix I suggest in the constructor.

File file = new File(this.getClass().getClassLoader().getResource("repositories.json").getFile());
repositoriesJson = file.toPath();

**Comment by decebals** [comment]
@sagarvilas 
I don't understand very clear where is the problem in your use case.
You have the possibility to specify the location of `repositoryJson` in the [constructor](https://github.com/pf4j/pf4j-update/blob/master/src/main/java/org/pf4j/update/UpdateManager.java#L70) of `UpdateManager`.
From your last comment I understand that your `repositoryJson` is available as resource, it's not the default location but I think that you can specify this location in the constructor of `UpdateManager`.

**Comment by sagarvilas** [comment]
Hi @decebals 
sorry for the confusion, I got your point that I can pass the path in constructor if it is not is the default location. My file is in default location but the condition in [refresh](https://github.com/pf4j/pf4j-update/blob/f932809cd37702ec0ad47afb3d733c54e13142a5/src/main/java/org/pf4j/update/UpdateManager.java#L222) fails and to fix that we will have to add the below lines at [this](https://github.com/pf4j/pf4j-update/blob/f932809cd37702ec0ad47afb3d733c54e13142a5/src/main/java/org/pf4j/update/UpdateManager.java#L67)
File file = new File(this.getClass().getClassLoader().getResource("repositories.json").getFile());
repositoriesJson = file.toPath(); 

As a workaround I can pass the same thing to constructor, but this will still be a bug.

**Comment by decebals** [comment]
It's still not clear for me. You have the possibility to pass the path of `repositoryJson` in [constructor](https://github.com/pf4j/pf4j-update/blob/master/src/main/java/org/pf4j/update/UpdateManager.java#L70).
The `repositoryJson:Path` is created by you and you should check if the path exists or not when you pass it in constructor.
The [line](https://github.com/pf4j/pf4j-update/blob/master/src/main/java/org/pf4j/update/UpdateManager.java#L222) invoked by you is very clear from my point of view (checl for null and call `Files.exists`). 
I don't understand where the problem may appear.

**Comment by sagarvilas** [comment]
Yes @decebals I can pass the repository path in constructor and use that, what I want to mention is if we are using the default location and not providing the path in constructor Files.exists will return false, I know your unit test and integration tests are not failing, but if you try to use the update module in a application Files.exists will return false at runtime even if the file is present in default location.

**Comment by decebals** [comment]
Can you add a screenshot (or add a text) to see where your `repositoryJson` is in file system?
If you want to use following line:
```
File file = new File(this.getClass().getClassLoader().getResource("repositories.json").getFile());
```

my feeling is that your `repositoryJson` file is in `src/main/resources` and this is not good (it's not the default location).

**Comment by sagarvilas** [comment]
Ok I understand what you are trying to say, i'll check that thank you.
