### ISSUE TITLE
org.slf4j:slf4j-log4j12 should have scope compile in pom.xml

### ISSUE THREAD

**Issue by pgrt** [pf4j/pf4j-update#56]
Hello,

In pom.xml, the `<scope>test</scope>` of org.slf4j:slf4j-log4j12 should be removed, as classes of slf4j are needed by classes of pf4j-update in src/main/ .

Best,
Pierre Gruet

**Comment by decebals** [comment]
In ` src/main` is enough `slf4j-api` that is transitive dependency from `pf4j`.
